steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-west1-docker.pkg.dev/mlops-475717/mlops-repo/sentiment-api:$SHORT_SHA'
      - '-t'
      - 'europe-west1-docker.pkg.dev/mlops-475717/mlops-repo/sentiment-api:latest'
      - 'sentiment-api'

  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'europe-west1-docker.pkg.dev/mlops-475717/mlops-repo/sentiment-api'

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'sentiment-api'
      - '--image=europe-west1-docker.pkg.dev/mlops-475717/mlops-repo/sentiment-api:$SHORT_SHA'
      - '--region=europe-west1'
      - '--platform=managed'
      - '--allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY
